### PR TITLE
Add GraphQL Inspector as a service

### PR DESCRIPTION
**Pull request by Urigo**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by caniszczyk** [comment]
Awesome, @Urigo maybe it's time to add the Guild as a GraphQL adopter too in the landscape :)?

**Comment by Urigo** [comment]
@caniszczyk I guess so! :)
We'll add it right after this one!

**Comment by Urigo** [comment]
@caniszczyk about the comment from the bot, that is true, inspector is both an open source library and a service...
What do you suggest we'll do?

**Comment by caniszczyk** [comment]
name unfortunately has to be unique so I'd recommend doing

'name: GraphQL Inspector Service' for it in the service section

**Comment by Urigo** [comment]
got it

**Comment by Urigo** [comment]
@caniszczyk should I just push also us as an adopter to this PR?

**Comment by caniszczyk** [comment]
@Urigo separate PR :)

**Pull request merged**
