### PR TITLE
Add Tailcall

### PR DESCRIPTION
**Pull request by varshith257**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

image

image

fixes https://github.com/tailcallhq/tailcall/issues/2750
/claim https://github.com/tailcallhq/tailcall/issues/2750

### CODE REVIEW

**Comment by varshith257** [comment]
Updated preview with logo clearly states the name of the project

image
image


cc: @tusharmath

**Comment by tusharmath** [comment]
LGTM!

**Comment by varshith257** [comment]
LGTM

**Comment by tusharmath** [comment]
@jorydotcom is there anything pending here?

**Comment by jorydotcom** [comment]
Thanks for stopping by and saying hello IRL today @varshith257!

**Comment by tusharmath** [comment]
I was me @jorydotcom 😀

**Comment by jorydotcom** [comment]
Haha oops nice to meet you @tusharmath 🎉🎉

**Pull request merged**
