### PR TITLE
Adopters added (1st half)

### PR DESCRIPTION
**Pull request by idvoretskyi**
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @caniszczyk

**Comment by caniszczyk** [comment]
@idvoretskyi this is a great start but we will wait for the build, my guess is you will need to add a lot more SVG logos to hosted_logos/

**Comment by dankohn** [comment]
Please don't add the Twitter if it's the same as what's in Crunchbase. It lets you skip a step. Also, it's generally easier to put a url in for the logo than download it to hosted_logos. The effect is the same, and you can always run `y host-images` later.

**Comment by idvoretskyi** [comment]
@caniszczyk missing svg's added.

@dankohn thanks, noted for the future.

**Comment by caniszczyk** [comment]
what's the error now?

FYI @idvoretskyi this is why I said to work in a piecemeal fashion versus one big PR

**Comment by dankohn** [comment]
Bad news: I don't know the cause of the error and I'm too lazy to do a binary search to find it. Running locally doesn't give any more info.
Good news: We've found a new corner case of bug reporting and will get it resolved.

https://github.com/cncf/landscapeapp/issues/413

**Comment by AndreyKozlov1984** [comment]
I've fixed an error message, so good luck with fixing svg images, @idvoretskyi

**Comment by idvoretskyi** [comment]
@AndreyKozlov1984 great, thanks!

Fixing now.

**Comment by idvoretskyi** [comment]
@AndreyKozlov1984 Is there any reason why `@Comparaonline` still shows an error?

I removed the Twitter line from the file - https://github.com/graphql/graphql-landscape/pull/35/files#diff-399df63a0dc3d44f4844720cbfc58105R314

**Comment by dankohn** [comment]
@idvoretskyi http://twitter.com/comparaonline doesn't exist. I removed it from Crunchbase so it should work next time you update. Or, you can set `twitter: null`.

**Comment by idvoretskyi** [comment]
@dankohn ok, thanks.

**Comment by idvoretskyi** [comment]
> Build failed because of:
> Cannot read property 'parents' of undefined

@dankohn @AndreyKozlov1984 what does this mean?

**Comment by AndreyKozlov1984** [comment]
Hi, @idvoretskyi , thank you for spotting this. I'm about to fix this message

**Comment by AndreyKozlov1984** [comment]
@idvoretskyi , the real issue is this:
```
FATAL: Duplicate item: ArangoDB Arangodb at path GraphQL Adopter / GraphQL Adopter
FATAL: Duplicate item: ArangoDB Arangodb at path GraphQL Adopter / GraphQL Adopter
```

**Comment by AndreyKozlov1984** [comment]
I am still fixing a code to properly report what is wrong.

**Comment by caniszczyk** [comment]
closing, instead https://github.com/graphql/graphql-landscape/pull/41

**Pull request closed without merging**
