### PR TITLE
Add TypeGraphQL to Tools

### PR DESCRIPTION
**Pull request by MichalLytek**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by MichalLytek** [comment]
Why I have to create a crunchbase profile for the GraphQL Landscape? 😕

**Comment by caniszczyk** [comment]
@MichalLytek yes, sorry it's a requirement, shouldn't be hard to do, someone at the end owns the project, which is you, so I'd just create https://www.crunchbase.com/organization/TypeGraphQL

Something like https://www.crunchbase.com/organization/openresty

**Comment by dankohn** [comment]
Explanation: https://github.com/cncf/landscapeapp/blob/master/README.md#crunchbase-requirement

**Comment by MichalLytek** [comment]
@caniszczyk How can I restart the netlify pipeline when I filled all the required data on crunchbase? 😕

**Comment by dankohn** [comment]
I triggered a rebuild but we need to wait an hour for the Crunchbase cache to expire.

**Comment by MichalLytek** [comment]
ping @dankohn 😃

**Comment by dankohn** [comment]
Please review and leave an LGTM.

**Comment by dankohn** [comment]
Also, the logo at https://twitter.com/MichalLytek/status/1188136728839774208 has more color variations than the SVG you uploaded. Do you have the more detailed logo as an SVG, AI, or EPS?

**Comment by MichalLytek** [comment]
> Do you have the more detailed logo as an SVG, AI, or EPS?

Unfortunately not, I only have a raster PNG image, so I converted/recreated into SVG to meet the requirements. Soon I will have a redesigned vector logo so I will updated this entry 😉

**Pull request merged**
